version: 2.1  # Use CircleCI 2.1 configuration

jobs:
  build:
    docker:
      # Specify the Docker image to run your build in
      - image: circleci/node:14.17.0  # You can use any version suitable for your project

    working_directory: ~/repo  # Directory where commands will run
    steps:
      - checkout  # Pull down your code from the repository

      - run:
          name: Install Dependencies
          command: npm install

      - run:
          name: Run Tests
          command: npm test

      - run:
          name: Build Project
          command: npm run build

      - persist_to_workspace:
          root: ~/repo
          paths:
            - build  # Save the built project for later jobs

  deploy:
    docker:
      - image: circleci/node:14.17.0

    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/repo  # Attach the workspace from the build job

      - run:
          name: Deploy to Production
          command: |
            # Add your deployment script here, for example:
            scp -r ./build/ user@your-server:/var/www/your-app

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build  # Run deploy only after build succeeds
